# Generated by Django 4.1 on 2022-08-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_id',
            new_name='player',
        ),
    ]
